# Generated by Django 5.2 on 2025-04-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_itemcarrinho_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(default='S/N', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rua',
            field=models.CharField(default='Não informado', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
