# Generated by Django 5.2 on 2025-04-12 02:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_usuario_cep_usuario_cidade_usuario_complemento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='em_oferta',
        ),
        migrations.AddField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cardapio.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão de Crédito'), ('mercado_pago', 'Mercado Pago')], default='mercado_pago', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total do Pedido')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('refunded', 'Reembolsado'), ('processing', 'Processando')], default='pending', max_length=20, verbose_name='Status do Pedido')),
                ('codigo_transacao', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código da Transação')),
                ('codigo_pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código PIX (se aplicável)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.itemcarrinho')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(related_name='pedidos', through='cardapio.PedidoItem', to='cardapio.itemcarrinho'),
        ),
    ]
