# Generated by Django 5.2 on 2025-04-12 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_alter_pedido_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cardapio.produto'),
        ),
    ]
