# Generated by Django 5.2 on 2025-04-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0007_alter_pedido_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
