# Generated by Django 5.2 on 2025-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0009_paymentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
