# Generated by Django 5.2 on 2025-06-03 18:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0010_arquivoteste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtoteste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.DeleteModel(
            name='ArquivoTeste',
        ),
    ]
