# Generated by Django 5.2 on 2025-06-03 23:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0012_alter_produto_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produtoteste',
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, default='url_da_imagem_padrao', max_length=255, null=True, verbose_name='image'),
        ),
    ]
